kind = "DojoContract"
class_hash = "0x13ddc72b488be3e89e072f0e99a0258abe7e4617a8880f4eeed6363f2e4346d"
original_class_hash = "0x13ddc72b488be3e89e072f0e99a0258abe7e4617a8880f4eeed6363f2e4346d"
base_class_hash = "0x0"
abi = "manifests/dev/base/abis/contracts/tonatuna-actions-31c51141.json"
reads = []
writes = []
init_calldata = []
tag = "tonatuna-actions"
systems = [
    "move",
    "spawn_fish",
    "spawn_multiple_fishes",
    "cast_fishing",
]
manifest_name = "tonatuna-actions-31c51141"
