kind = "DojoContract"
class_hash = "0x18c3c08d7f141397f851da461765472c1f370641613d897a6dbb8991cc8597d"
original_class_hash = "0x18c3c08d7f141397f851da461765472c1f370641613d897a6dbb8991cc8597d"
base_class_hash = "0x0"
abi = "manifests/dev/base/abis/contracts/tonatuna-actions-31c51141.json"
reads = []
writes = []
init_calldata = []
tag = "tonatuna-actions"
systems = [
    "move",
    "spawn_fish",
    "spawn_multiple_fishes",
    "cast_fishing",
    "reel_by_revealing",
]
manifest_name = "tonatuna-actions-31c51141"
