kind = "DojoContract"
class_hash = "0x1ab10e86620d5561e590c327d52762558a4b15fea2dd8696685e972b5584a93"
original_class_hash = "0x1ab10e86620d5561e590c327d52762558a4b15fea2dd8696685e972b5584a93"
base_class_hash = "0x0"
abi = "manifests/dev/base/abis/contracts/tonatuna-actions-31c51141.json"
reads = []
writes = []
init_calldata = []
tag = "tonatuna-actions"
systems = [
    "reset_daily_attempts",
    "buy_baits",
    "move",
    "spawn_fish",
    "spawn_multiple_fishes",
    "play",
    "cast_fishing",
    "reel_by_revealing",
    "catch_the_fish",
]
manifest_name = "tonatuna-actions-31c51141"
