kind = "DojoContract"
class_hash = "0x73807aead986a4bf1e689a6740201a823db0934c1bb1d2a57afb4bd35e1cd81"
original_class_hash = "0x73807aead986a4bf1e689a6740201a823db0934c1bb1d2a57afb4bd35e1cd81"
base_class_hash = "0x0"
abi = "manifests/dev/base/abis/contracts/tonatuna-actions-31c51141.json"
reads = []
writes = []
init_calldata = []
tag = "tonatuna-actions"
systems = [
    "move",
    "spawn_fish",
]
manifest_name = "tonatuna-actions-31c51141"
