kind = "DojoContract"
class_hash = "0xe5ea3770d858215f352aa5bef3264cf3a7fc019fcc04adf5152ae37cb2f43"
original_class_hash = "0xe5ea3770d858215f352aa5bef3264cf3a7fc019fcc04adf5152ae37cb2f43"
base_class_hash = "0x0"
abi = "manifests/dev/base/abis/contracts/tonatuna-actions-31c51141.json"
reads = []
writes = []
init_calldata = []
tag = "tonatuna-actions"
systems = [
    "reset_daily_attempts",
    "buy_baits",
    "move",
    "spawn_fish",
    "spawn_multiple_fishes",
    "cast_fishing",
    "reel_by_revealing",
    "catch_the_fish",
]
manifest_name = "tonatuna-actions-31c51141"
