kind = "DojoContract"
class_hash = "0x1c848500c26e1f2ef3c0c42ac0b4ed98a1a54eeb907759ca36235a8568e6430"
original_class_hash = "0x1c848500c26e1f2ef3c0c42ac0b4ed98a1a54eeb907759ca36235a8568e6430"
base_class_hash = "0x0"
abi = "manifests/dev/base/abis/contracts/tonatuna-actions-31c51141.json"
reads = []
writes = []
init_calldata = []
tag = "tonatuna-actions"
systems = [
    "reset_daily_attempts",
    "buy_baits",
    "move",
    "spawn_fish",
    "spawn_multiple_fishes",
    "play",
    "cast_fishing",
    "reel_by_revealing",
    "catch_the_fish",
]
manifest_name = "tonatuna-actions-31c51141"
