[world]
kind = "WorldContract"
class_hash = "0x3715f072aa1c07be724249fcda8b0322687f6c5c585eebc4402d162649c707c"
original_class_hash = "0x3715f072aa1c07be724249fcda8b0322687f6c5c585eebc4402d162649c707c"
abi = "manifests/dev/deployment/abis/dojo-world.json"
address = "0x11e23a4568363aa10dce5254094f893e95cbd700915fd0d0c30a59f218d2a9d"
transaction_hash = "0x430e559d062bd14a063a74972596bbec6507b7d5b0bebd588057397171aaafb"
block_number = 3
seed = "tonatuna"
manifest_name = "dojo-world"

[world.metadata]
profile_name = "dev"
rpc_url = "http://0.0.0.0:5050/"

[base]
kind = "Class"
class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
original_class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
abi = "manifests/dev/deployment/abis/dojo-base.json"
tag = "dojo-base"
manifest_name = "dojo-base"

[[contracts]]
kind = "DojoContract"
address = "0x2fdd8dc923c575334bfce376871fb80b89bcba892d9322ba9fb5db698146c9b"
class_hash = "0xe5ea3770d858215f352aa5bef3264cf3a7fc019fcc04adf5152ae37cb2f43"
original_class_hash = "0xe5ea3770d858215f352aa5bef3264cf3a7fc019fcc04adf5152ae37cb2f43"
base_class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
abi = "manifests/dev/deployment/abis/contracts/tonatuna-actions-31c51141.json"
reads = []
writes = ["ns:tonatuna"]
init_calldata = []
tag = "tonatuna-actions"
systems = [
    "reset_daily_attempts",
    "buy_baits",
    "move",
    "spawn_fish",
    "spawn_multiple_fishes",
    "cast_fishing",
    "reel_by_revealing",
    "catch_the_fish",
]
manifest_name = "tonatuna-actions-31c51141"

[[models]]
kind = "DojoModel"
class_hash = "0x7df68e024fc00da2b03d6c3c8e38f6e839dbd8fdfa44b527a97083c5c53ce0b"
original_class_hash = "0x7df68e024fc00da2b03d6c3c8e38f6e839dbd8fdfa44b527a97083c5c53ce0b"
abi = "manifests/dev/deployment/abis/models/tonatuna-Commitment-5626dabb.json"
tag = "tonatuna-Commitment"
qualified_path = "tonatuna::models::index::commitment"
manifest_name = "tonatuna-Commitment-5626dabb"

[[models.members]]
name = "player_id"
type = "felt252"
key = true

[[models.members]]
name = "fish_pond_id"
type = "u32"
key = true

[[models.members]]
name = "value"
type = "felt252"
key = false

[[models.members]]
name = "status"
type = "u8"
key = false

[[models.members]]
name = "timestamp"
type = "u64"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x1890d147565b501edc040aeed98f4c024c7c0170eeb47e7178a22c1e2a9254d"
original_class_hash = "0x1890d147565b501edc040aeed98f4c024c7c0170eeb47e7178a22c1e2a9254d"
abi = "manifests/dev/deployment/abis/models/tonatuna-Fish-62d9a085.json"
tag = "tonatuna-Fish"
qualified_path = "tonatuna::models::index::fish"
manifest_name = "tonatuna-Fish-62d9a085"

[[models.members]]
name = "fish_pond_id"
type = "u32"
key = true

[[models.members]]
name = "fish_id"
type = "u32"
key = true

[[models.members]]
name = "position"
type = "Vec2"
key = false

[[models.members]]
name = "weight"
type = "u32"
key = false

[[models.members]]
name = "status"
type = "u8"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x4bb183919b5e0be0bd37154a516acdde9927eef061e886851a7c56680a0c714"
original_class_hash = "0x4bb183919b5e0be0bd37154a516acdde9927eef061e886851a7c56680a0c714"
abi = "manifests/dev/deployment/abis/models/tonatuna-FishPond-6253e2c7.json"
tag = "tonatuna-FishPond"
qualified_path = "tonatuna::models::index::fish_pond"
manifest_name = "tonatuna-FishPond-6253e2c7"

[[models.members]]
name = "id"
type = "u32"
key = true

[[models.members]]
name = "fish_population"
type = "u32"
key = false

[[models.members]]
name = "daily_catch_limit"
type = "u32"
key = false

[[models.members]]
name = "rare_fish_chance"
type = "u8"
key = false

[[models.members]]
name = "daily_catches"
type = "u32"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x5d1e34fed7ae0fb2b98222f698af52ff1f528dd2bc7c9e66722e336313cb7d6"
original_class_hash = "0x5d1e34fed7ae0fb2b98222f698af52ff1f528dd2bc7c9e66722e336313cb7d6"
abi = "manifests/dev/deployment/abis/models/tonatuna-Player-24470676.json"
tag = "tonatuna-Player"
qualified_path = "tonatuna::models::index::player"
manifest_name = "tonatuna-Player-24470676"

[[models.members]]
name = "id"
type = "felt252"
key = true

[[models.members]]
name = "name"
type = "felt252"
key = false

[[models.members]]
name = "bait_balance"
type = "u32"
key = false

[[models.members]]
name = "fish_caught"
type = "u32"
key = false

[[models.members]]
name = "daily_attempts"
type = "u8"
key = false

[[models.members]]
name = "position"
type = "Vec2"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x4092ff33b03f32a3f143466d0e67b5718b62549d83bbf32b0317f5da22ceeb6"
original_class_hash = "0x4092ff33b03f32a3f143466d0e67b5718b62549d83bbf32b0317f5da22ceeb6"
abi = "manifests/dev/deployment/abis/models/tonatuna-RevealHistory-ca67e456.json"
tag = "tonatuna-RevealHistory"
qualified_path = "tonatuna::models::index::reveal_history"
manifest_name = "tonatuna-RevealHistory-ca67e456"

[[models.members]]
name = "fish_pond_id"
type = "u32"
key = true

[[models.members]]
name = "fish_id"
type = "u32"
key = true

[[models.members]]
name = "commit_timestamp"
type = "u64"
key = false

[[models.members]]
name = "reveal_timestamp"
type = "u64"
key = false

[[models.members]]
name = "count"
type = "u32"
key = false
