[world]
kind = "WorldContract"
class_hash = "0x3715f072aa1c07be724249fcda8b0322687f6c5c585eebc4402d162649c707c"
original_class_hash = "0x3715f072aa1c07be724249fcda8b0322687f6c5c585eebc4402d162649c707c"
abi = "manifests/dev/deployment/abis/dojo-world.json"
address = "0x11e23a4568363aa10dce5254094f893e95cbd700915fd0d0c30a59f218d2a9d"
seed = "tonatuna"
manifest_name = "dojo-world"

[world.metadata]
profile_name = "dev"
rpc_url = "https://api.cartridge.gg/x/tonatuna-alpha-v1/katana"

[base]
kind = "Class"
class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
original_class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
abi = "manifests/dev/deployment/abis/dojo-base.json"
tag = "dojo-base"
manifest_name = "dojo-base"

[[contracts]]
kind = "DojoContract"
class_hash = "0x5425bcd6d88ddc65f34468f6ff3cd3068ed3bf1983ab733ecfc61478556cd4"
original_class_hash = "0x5425bcd6d88ddc65f34468f6ff3cd3068ed3bf1983ab733ecfc61478556cd4"
base_class_hash = "0x0"
abi = "manifests/dev/deployment/abis/contracts/tonatuna-actions-31c51141.json"
reads = []
writes = ["ns:tonatuna"]
init_calldata = []
tag = "tonatuna-actions"
systems = ["create_fish_pond"]
manifest_name = "tonatuna-actions-31c51141"

[[models]]
kind = "DojoModel"
class_hash = "0x4bb183919b5e0be0bd37154a516acdde9927eef061e886851a7c56680a0c714"
original_class_hash = "0x4bb183919b5e0be0bd37154a516acdde9927eef061e886851a7c56680a0c714"
abi = "manifests/dev/deployment/abis/models/tonatuna-FishPond-6253e2c7.json"
tag = "tonatuna-FishPond"
qualified_path = "tonatuna::models::index::fish_pond"
manifest_name = "tonatuna-FishPond-6253e2c7"

[[models.members]]
name = "id"
type = "u32"
key = true

[[models.members]]
name = "fish_population"
type = "u32"
key = false

[[models.members]]
name = "daily_catch_limit"
type = "u32"
key = false

[[models.members]]
name = "rare_fish_chance"
type = "u8"
key = false

[[models.members]]
name = "daily_catches"
type = "u32"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x478a247a5f54f03ed440231e5ada86ac9faa77ef9f1ab0f7ff740d37887eab0"
original_class_hash = "0x478a247a5f54f03ed440231e5ada86ac9faa77ef9f1ab0f7ff740d37887eab0"
abi = "manifests/dev/deployment/abis/models/tonatuna-Player-24470676.json"
tag = "tonatuna-Player"
qualified_path = "tonatuna::models::index::player"
manifest_name = "tonatuna-Player-24470676"

[[models.members]]
name = "id"
type = "felt252"
key = true

[[models.members]]
name = "name"
type = "felt252"
key = false

[[models.members]]
name = "bait_balance"
type = "u32"
key = false

[[models.members]]
name = "fish_caught"
type = "u32"
key = false

[[models.members]]
name = "daily_attempts"
type = "u8"
key = false
