[world]
kind = "WorldContract"
class_hash = "0x458d0ce5b14a4844092bdb62050f462d53362304a13febbac6d973691d61be2"
original_class_hash = "0x458d0ce5b14a4844092bdb62050f462d53362304a13febbac6d973691d61be2"
abi = "manifests/dev/deployment/abis/dojo-world.json"
address = "0x65c3cc2c4287630427181a60cd9301bc4c84a5cdb2457cd7b2a8d1279bd901e"
transaction_hash = "0x72b8907e8cfb88bb4071c713aa533aff4fe948d507c169e4b77d4327174ef17"
block_number = 3
seed = "tonatuna"
manifest_name = "dojo-world"

[world.metadata]
profile_name = "dev"
rpc_url = "https://api.cartridge.gg/x/tonatuna/katana"

[base]
kind = "Class"
class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
original_class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
abi = "manifests/dev/deployment/abis/dojo-base.json"
tag = "dojo-base"
manifest_name = "dojo-base"

[[contracts]]
kind = "DojoContract"
address = "0x426feaf880a9d54f5b52a3f0169bb4502a7b93d0d6db12aa9b578fc55894a35"
class_hash = "0x36cd00731e578f9d498b5a1a44d910bbefb3c52220320903e2982f66e51c4a9"
original_class_hash = "0x36cd00731e578f9d498b5a1a44d910bbefb3c52220320903e2982f66e51c4a9"
base_class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
abi = "manifests/dev/deployment/abis/contracts/tonatuna-actions-31c51141.json"
reads = []
writes = ["ns:tonatuna"]
init_calldata = []
tag = "tonatuna-actions"
systems = [
    "spawn",
    "move",
]
manifest_name = "tonatuna-actions-31c51141"

[[models]]
kind = "DojoModel"
class_hash = "0x3b98b467b59555f321c490645a78765ca8ba1edaee023fb0db47682c48a18e5"
original_class_hash = "0x3b98b467b59555f321c490645a78765ca8ba1edaee023fb0db47682c48a18e5"
abi = "manifests/dev/deployment/abis/models/tonatuna-DirectionsAvailable-4cb6d4a7.json"
tag = "tonatuna-DirectionsAvailable"
manifest_name = "tonatuna-DirectionsAvailable-4cb6d4a7"

[[models.members]]
name = "player"
type = "ContractAddress"
key = true

[[models.members]]
name = "directions"
type = "Array<Direction>"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x4c4c0b25daf190eea9de98667ef946b34bb7e5ac8b73aa3833572c1cdf8966b"
original_class_hash = "0x4c4c0b25daf190eea9de98667ef946b34bb7e5ac8b73aa3833572c1cdf8966b"
abi = "manifests/dev/deployment/abis/models/tonatuna-Moved-20af9a00.json"
tag = "tonatuna-Moved"
manifest_name = "tonatuna-Moved-20af9a00"

[[models.members]]
name = "player"
type = "ContractAddress"
key = true

[[models.members]]
name = "direction"
type = "Direction"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x46309a9ebf09823640924578bad2d0d0b75a5c1ac50fe4dc2c1b5b65426469e"
original_class_hash = "0x46309a9ebf09823640924578bad2d0d0b75a5c1ac50fe4dc2c1b5b65426469e"
abi = "manifests/dev/deployment/abis/models/tonatuna-Moves-2cf8f0f8.json"
tag = "tonatuna-Moves"
manifest_name = "tonatuna-Moves-2cf8f0f8"

[[models.members]]
name = "player"
type = "ContractAddress"
key = true

[[models.members]]
name = "remaining"
type = "u8"
key = false

[[models.members]]
name = "last_direction"
type = "Direction"
key = false

[[models.members]]
name = "can_move"
type = "bool"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x7d25c8545f279fb7ccf71241d0c395176d75a6d7207c321d370154bdda54dc5"
original_class_hash = "0x7d25c8545f279fb7ccf71241d0c395176d75a6d7207c321d370154bdda54dc5"
abi = "manifests/dev/deployment/abis/models/tonatuna-Position-50b164f1.json"
tag = "tonatuna-Position"
manifest_name = "tonatuna-Position-50b164f1"

[[models.members]]
name = "player"
type = "ContractAddress"
key = true

[[models.members]]
name = "vec"
type = "Vec2"
key = false
