// Generated by dojo-bindgen on Mon, 26 Aug 2024 15:13:33 +0000. Do not modify this file manually.
// Import the necessary types from the recs SDK
// generate again with `sozo build --typescript`
import { Account, byteArray } from "starknet";
import { DojoProvider } from "@dojoengine/core";
import * as models from "./models.gen";

export type IWorld = Awaited<ReturnType<typeof setupWorld>>;

export async function setupWorld(provider: DojoProvider) {
  // System definitions for `tonatuna-actions` contract
  function actions() {
    const contract_name = "actions";

    // Call the `create_fish_pond` system with the specified Account and calldata
    const create_fish_pond = async (props: { account: Account }) => {
      try {
        return await provider.execute(
          props.account,
          {
            contractName: contract_name,
            entrypoint: "create_fish_pond",
            calldata: [],
          },
          "tonatuna",
        );
      } catch (error) {
        console.error("Error executing create_fish_pond:", error);
        throw error;
      }
    };

    return {
      create_fish_pond,
    };
  }

  return {
    actions: actions(),
  };
}
