[world]
kind = "WorldContract"
class_hash = "0x3715f072aa1c07be724249fcda8b0322687f6c5c585eebc4402d162649c707c"
original_class_hash = "0x3715f072aa1c07be724249fcda8b0322687f6c5c585eebc4402d162649c707c"
abi = "manifests/sepolia/deployment/abis/dojo-world.json"
address = "0x11e23a4568363aa10dce5254094f893e95cbd700915fd0d0c30a59f218d2a9d"
transaction_hash = "0x220f963b42ef0e32095e96f394ed3d6bcf128023583395d51498af55084360f"
seed = "tonatuna"
manifest_name = "dojo-world"

[world.metadata]
profile_name = "sepolia"
rpc_url = "https://starknet-sepolia.public.blastapi.io/rpc/v0_7"

[base]
kind = "Class"
class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
original_class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
abi = "manifests/sepolia/deployment/abis/dojo-base.json"
tag = "dojo-base"
manifest_name = "dojo-base"

[[contracts]]
kind = "DojoContract"
address = "0x2fdd8dc923c575334bfce376871fb80b89bcba892d9322ba9fb5db698146c9b"
class_hash = "0x69cc965f5827084f646708043de8a63f6ca3303750c4bf6ecd501e2e419ce9f"
original_class_hash = "0x69cc965f5827084f646708043de8a63f6ca3303750c4bf6ecd501e2e419ce9f"
base_class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
abi = "manifests/sepolia/deployment/abis/contracts/tonatuna-actions-31c51141.json"
reads = []
writes = ["ns:tonatuna"]
init_calldata = []
tag = "tonatuna-actions"
systems = [
    "reset_daily_attempts",
    "buy_baits",
    "move",
    "spawn_fish",
    "spawn_multiple_fishes",
    "cast_fishing",
    "reel_by_revealing",
    "catch_the_fish",
]
manifest_name = "tonatuna-actions-31c51141"

[[models]]
kind = "DojoModel"
class_hash = "0x222d10acee2a214aed878d06010385b8624a48bbb61a8bc9a777f8facd9a36d"
original_class_hash = "0x222d10acee2a214aed878d06010385b8624a48bbb61a8bc9a777f8facd9a36d"
abi = "manifests/sepolia/deployment/abis/models/origami_token-ERC20AllowanceModel-4fcf1991.json"
tag = "origami_token-ERC20AllowanceModel"
qualified_path = "origami_token::components::token::erc20::erc20_allowance::erc_20_allowance_model"
manifest_name = "origami_token-ERC20AllowanceModel-4fcf1991"

[[models.members]]
name = "token"
type = "ContractAddress"
key = true

[[models.members]]
name = "owner"
type = "ContractAddress"
key = true

[[models.members]]
name = "spender"
type = "ContractAddress"
key = true

[[models.members]]
name = "amount"
type = "u256"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x38c3c9f4ec3feea51cee2ec9be6592b50f711f5fa39e5b4f0ca0e770675505e"
original_class_hash = "0x38c3c9f4ec3feea51cee2ec9be6592b50f711f5fa39e5b4f0ca0e770675505e"
abi = "manifests/sepolia/deployment/abis/models/origami_token-ERC20BalanceModel-da267235.json"
tag = "origami_token-ERC20BalanceModel"
qualified_path = "origami_token::components::token::erc20::erc20_balance::erc_20_balance_model"
manifest_name = "origami_token-ERC20BalanceModel-da267235"

[[models.members]]
name = "token"
type = "ContractAddress"
key = true

[[models.members]]
name = "account"
type = "ContractAddress"
key = true

[[models.members]]
name = "amount"
type = "u256"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x209edb9bdfa6fbd1f99ab521aa31319316615ca7fa31a61a2daf24c8b1b6706"
original_class_hash = "0x209edb9bdfa6fbd1f99ab521aa31319316615ca7fa31a61a2daf24c8b1b6706"
abi = "manifests/sepolia/deployment/abis/models/origami_token-ERC20BridgeableModel-28075fe4.json"
tag = "origami_token-ERC20BridgeableModel"
qualified_path = "origami_token::components::token::erc20::erc20_bridgeable::erc_20_bridgeable_model"
manifest_name = "origami_token-ERC20BridgeableModel-28075fe4"

[[models.members]]
name = "token"
type = "ContractAddress"
key = true

[[models.members]]
name = "l2_bridge_address"
type = "ContractAddress"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x2a9e6b7d401e8c9fa77e5221dce4f049334ce8ed4d7a53f88adf72b3af968eb"
original_class_hash = "0x2a9e6b7d401e8c9fa77e5221dce4f049334ce8ed4d7a53f88adf72b3af968eb"
abi = "manifests/sepolia/deployment/abis/models/origami_token-ERC20MetadataModel-3368c0e3.json"
tag = "origami_token-ERC20MetadataModel"
qualified_path = "origami_token::components::token::erc20::erc20_metadata::erc_20_metadata_model"
manifest_name = "origami_token-ERC20MetadataModel-3368c0e3"

[[models.members]]
name = "token"
type = "ContractAddress"
key = true

[[models.members]]
name = "name"
type = "ByteArray"
key = false

[[models.members]]
name = "symbol"
type = "ByteArray"
key = false

[[models.members]]
name = "decimals"
type = "u8"
key = false

[[models.members]]
name = "total_supply"
type = "u256"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x36dc2b76dcd77b58fe987c0b8836c2ce7fa08cb9d44838634218fad353bec83"
original_class_hash = "0x36dc2b76dcd77b58fe987c0b8836c2ce7fa08cb9d44838634218fad353bec83"
abi = "manifests/sepolia/deployment/abis/models/origami_token-ERC721BalanceModel-246a8e17.json"
tag = "origami_token-ERC721BalanceModel"
qualified_path = "origami_token::components::token::erc721::erc721_balance::erc_721_balance_model"
manifest_name = "origami_token-ERC721BalanceModel-246a8e17"

[[models.members]]
name = "token"
type = "ContractAddress"
key = true

[[models.members]]
name = "account"
type = "ContractAddress"
key = true

[[models.members]]
name = "amount"
type = "u128"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x5d3394057bbdf2262c0ba952ec0bbc13b8a315ad8bd9e684650225abc4152ac"
original_class_hash = "0x5d3394057bbdf2262c0ba952ec0bbc13b8a315ad8bd9e684650225abc4152ac"
abi = "manifests/sepolia/deployment/abis/models/origami_token-ERC721EnumerableIndexModel-1a4200e7.json"
tag = "origami_token-ERC721EnumerableIndexModel"
qualified_path = "origami_token::components::token::erc721::erc721_enumerable::erc_721_enumerable_index_model"
manifest_name = "origami_token-ERC721EnumerableIndexModel-1a4200e7"

[[models.members]]
name = "token"
type = "ContractAddress"
key = true

[[models.members]]
name = "index"
type = "u128"
key = true

[[models.members]]
name = "token_id"
type = "u128"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x2fd76867b943befb036da828bd1d2bec2386863ad70aafa770360c5b3e9acfc"
original_class_hash = "0x2fd76867b943befb036da828bd1d2bec2386863ad70aafa770360c5b3e9acfc"
abi = "manifests/sepolia/deployment/abis/models/origami_token-ERC721EnumerableOwnerIndexModel-573cb336.json"
tag = "origami_token-ERC721EnumerableOwnerIndexModel"
qualified_path = "origami_token::components::token::erc721::erc721_enumerable::erc_721_enumerable_owner_index_model"
manifest_name = "origami_token-ERC721EnumerableOwnerIndexModel-573cb336"

[[models.members]]
name = "token"
type = "ContractAddress"
key = true

[[models.members]]
name = "owner"
type = "ContractAddress"
key = true

[[models.members]]
name = "index"
type = "u128"
key = true

[[models.members]]
name = "token_id"
type = "u128"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x45871731d39993b19571f03348d6932fba0445f6eb94e1e37d2db5c4474d61c"
original_class_hash = "0x45871731d39993b19571f03348d6932fba0445f6eb94e1e37d2db5c4474d61c"
abi = "manifests/sepolia/deployment/abis/models/origami_token-ERC721EnumerableOwnerTokenModel-74966560.json"
tag = "origami_token-ERC721EnumerableOwnerTokenModel"
qualified_path = "origami_token::components::token::erc721::erc721_enumerable::erc_721_enumerable_owner_token_model"
manifest_name = "origami_token-ERC721EnumerableOwnerTokenModel-74966560"

[[models.members]]
name = "token"
type = "ContractAddress"
key = true

[[models.members]]
name = "owner"
type = "ContractAddress"
key = true

[[models.members]]
name = "token_id"
type = "u128"
key = true

[[models.members]]
name = "index"
type = "u128"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0xf5a9baf34c431fc11c05e15ddff7eb4750847ada1db57528ddad2966a7f3ec"
original_class_hash = "0xf5a9baf34c431fc11c05e15ddff7eb4750847ada1db57528ddad2966a7f3ec"
abi = "manifests/sepolia/deployment/abis/models/origami_token-ERC721EnumerableTokenModel-5c383d9f.json"
tag = "origami_token-ERC721EnumerableTokenModel"
qualified_path = "origami_token::components::token::erc721::erc721_enumerable::erc_721_enumerable_token_model"
manifest_name = "origami_token-ERC721EnumerableTokenModel-5c383d9f"

[[models.members]]
name = "token"
type = "ContractAddress"
key = true

[[models.members]]
name = "token_id"
type = "u128"
key = true

[[models.members]]
name = "index"
type = "u128"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x476254a3660ac696486628f6fb9c531a94de4b0addcc00bc43eafc207638968"
original_class_hash = "0x476254a3660ac696486628f6fb9c531a94de4b0addcc00bc43eafc207638968"
abi = "manifests/sepolia/deployment/abis/models/origami_token-ERC721EnumerableTotalModel-5674a124.json"
tag = "origami_token-ERC721EnumerableTotalModel"
qualified_path = "origami_token::components::token::erc721::erc721_enumerable::erc_721_enumerable_total_model"
manifest_name = "origami_token-ERC721EnumerableTotalModel-5674a124"

[[models.members]]
name = "token"
type = "ContractAddress"
key = true

[[models.members]]
name = "total_supply"
type = "u128"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x4310a938ba169a6d12cd0aa9dbeaf2992ddc4b55621bdeb883c0b43a3726d6d"
original_class_hash = "0x4310a938ba169a6d12cd0aa9dbeaf2992ddc4b55621bdeb883c0b43a3726d6d"
abi = "manifests/sepolia/deployment/abis/models/origami_token-ERC721MetaModel-423fffaa.json"
tag = "origami_token-ERC721MetaModel"
qualified_path = "origami_token::components::token::erc721::erc721_metadata::erc_721_meta_model"
manifest_name = "origami_token-ERC721MetaModel-423fffaa"

[[models.members]]
name = "token"
type = "ContractAddress"
key = true

[[models.members]]
name = "name"
type = "ByteArray"
key = false

[[models.members]]
name = "symbol"
type = "ByteArray"
key = false

[[models.members]]
name = "base_uri"
type = "ByteArray"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x29f6fcd504ae293bec1139611e0fe870deda9be6a41ef7e1ffacfa5c76c4dd5"
original_class_hash = "0x29f6fcd504ae293bec1139611e0fe870deda9be6a41ef7e1ffacfa5c76c4dd5"
abi = "manifests/sepolia/deployment/abis/models/origami_token-ERC721OperatorApprovalModel-1083d4d1.json"
tag = "origami_token-ERC721OperatorApprovalModel"
qualified_path = "origami_token::components::token::erc721::erc721_approval::erc_721_operator_approval_model"
manifest_name = "origami_token-ERC721OperatorApprovalModel-1083d4d1"

[[models.members]]
name = "token"
type = "ContractAddress"
key = true

[[models.members]]
name = "owner"
type = "ContractAddress"
key = true

[[models.members]]
name = "operator"
type = "ContractAddress"
key = true

[[models.members]]
name = "approved"
type = "bool"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x356e5dea0e7529f6c2617074b151c03b23cfb408d0a1ef8e123c226502cf115"
original_class_hash = "0x356e5dea0e7529f6c2617074b151c03b23cfb408d0a1ef8e123c226502cf115"
abi = "manifests/sepolia/deployment/abis/models/origami_token-ERC721OwnerModel-61577880.json"
tag = "origami_token-ERC721OwnerModel"
qualified_path = "origami_token::components::token::erc721::erc721_owner::erc_721_owner_model"
manifest_name = "origami_token-ERC721OwnerModel-61577880"

[[models.members]]
name = "token"
type = "ContractAddress"
key = true

[[models.members]]
name = "token_id"
type = "u128"
key = true

[[models.members]]
name = "address"
type = "ContractAddress"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x290d67abdcfd26f1d9768cec5ff48842cd405ce33417c6e8a212da0baa77e86"
original_class_hash = "0x290d67abdcfd26f1d9768cec5ff48842cd405ce33417c6e8a212da0baa77e86"
abi = "manifests/sepolia/deployment/abis/models/origami_token-ERC721TokenApprovalModel-560d5854.json"
tag = "origami_token-ERC721TokenApprovalModel"
qualified_path = "origami_token::components::token::erc721::erc721_approval::erc_721_token_approval_model"
manifest_name = "origami_token-ERC721TokenApprovalModel-560d5854"

[[models.members]]
name = "token"
type = "ContractAddress"
key = true

[[models.members]]
name = "token_id"
type = "u128"
key = true

[[models.members]]
name = "address"
type = "ContractAddress"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x43c7452e01d3ecb9f7460490397bd17c0d3461bd322d93bbfac4925dc9ee1ed"
original_class_hash = "0x43c7452e01d3ecb9f7460490397bd17c0d3461bd322d93bbfac4925dc9ee1ed"
abi = "manifests/sepolia/deployment/abis/models/origami_token-InitializableModel-5c624096.json"
tag = "origami_token-InitializableModel"
qualified_path = "origami_token::components::security::initializable::initializable_model"
manifest_name = "origami_token-InitializableModel-5c624096"

[[models.members]]
name = "token"
type = "ContractAddress"
key = true

[[models.members]]
name = "initialized"
type = "bool"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x25d17f5223a69a8f5a4b9bdd2bba1121a9da6e5bdb83592402943158e5946b9"
original_class_hash = "0x25d17f5223a69a8f5a4b9bdd2bba1121a9da6e5bdb83592402943158e5946b9"
abi = "manifests/sepolia/deployment/abis/models/origami_token-SRC5Model-72fc8945.json"
tag = "origami_token-SRC5Model"
qualified_path = "origami_token::components::introspection::src5::src_5_model"
manifest_name = "origami_token-SRC5Model-72fc8945"

[[models.members]]
name = "token"
type = "ContractAddress"
key = true

[[models.members]]
name = "interface_id"
type = "felt252"
key = true

[[models.members]]
name = "supports"
type = "bool"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x7df68e024fc00da2b03d6c3c8e38f6e839dbd8fdfa44b527a97083c5c53ce0b"
original_class_hash = "0x7df68e024fc00da2b03d6c3c8e38f6e839dbd8fdfa44b527a97083c5c53ce0b"
abi = "manifests/sepolia/deployment/abis/models/tonatuna-Commitment-5626dabb.json"
tag = "tonatuna-Commitment"
qualified_path = "tonatuna::models::index::commitment"
manifest_name = "tonatuna-Commitment-5626dabb"

[[models.members]]
name = "player_id"
type = "felt252"
key = true

[[models.members]]
name = "fish_pond_id"
type = "u32"
key = true

[[models.members]]
name = "value"
type = "felt252"
key = false

[[models.members]]
name = "status"
type = "u8"
key = false

[[models.members]]
name = "timestamp"
type = "u64"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x1890d147565b501edc040aeed98f4c024c7c0170eeb47e7178a22c1e2a9254d"
original_class_hash = "0x1890d147565b501edc040aeed98f4c024c7c0170eeb47e7178a22c1e2a9254d"
abi = "manifests/sepolia/deployment/abis/models/tonatuna-Fish-62d9a085.json"
tag = "tonatuna-Fish"
qualified_path = "tonatuna::models::index::fish"
manifest_name = "tonatuna-Fish-62d9a085"

[[models.members]]
name = "fish_pond_id"
type = "u32"
key = true

[[models.members]]
name = "fish_id"
type = "u32"
key = true

[[models.members]]
name = "position"
type = "Vec2"
key = false

[[models.members]]
name = "weight"
type = "u32"
key = false

[[models.members]]
name = "status"
type = "u8"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x4bb183919b5e0be0bd37154a516acdde9927eef061e886851a7c56680a0c714"
original_class_hash = "0x4bb183919b5e0be0bd37154a516acdde9927eef061e886851a7c56680a0c714"
abi = "manifests/sepolia/deployment/abis/models/tonatuna-FishPond-6253e2c7.json"
tag = "tonatuna-FishPond"
qualified_path = "tonatuna::models::index::fish_pond"
manifest_name = "tonatuna-FishPond-6253e2c7"

[[models.members]]
name = "id"
type = "u32"
key = true

[[models.members]]
name = "fish_population"
type = "u32"
key = false

[[models.members]]
name = "daily_catch_limit"
type = "u32"
key = false

[[models.members]]
name = "rare_fish_chance"
type = "u8"
key = false

[[models.members]]
name = "daily_catches"
type = "u32"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x5d1e34fed7ae0fb2b98222f698af52ff1f528dd2bc7c9e66722e336313cb7d6"
original_class_hash = "0x5d1e34fed7ae0fb2b98222f698af52ff1f528dd2bc7c9e66722e336313cb7d6"
abi = "manifests/sepolia/deployment/abis/models/tonatuna-Player-24470676.json"
tag = "tonatuna-Player"
qualified_path = "tonatuna::models::index::player"
manifest_name = "tonatuna-Player-24470676"

[[models.members]]
name = "id"
type = "felt252"
key = true

[[models.members]]
name = "name"
type = "felt252"
key = false

[[models.members]]
name = "bait_balance"
type = "u32"
key = false

[[models.members]]
name = "fish_caught"
type = "u32"
key = false

[[models.members]]
name = "daily_attempts"
type = "u8"
key = false

[[models.members]]
name = "position"
type = "Vec2"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x4092ff33b03f32a3f143466d0e67b5718b62549d83bbf32b0317f5da22ceeb6"
original_class_hash = "0x4092ff33b03f32a3f143466d0e67b5718b62549d83bbf32b0317f5da22ceeb6"
abi = "manifests/sepolia/deployment/abis/models/tonatuna-RevealHistory-ca67e456.json"
tag = "tonatuna-RevealHistory"
qualified_path = "tonatuna::models::index::reveal_history"
manifest_name = "tonatuna-RevealHistory-ca67e456"

[[models.members]]
name = "fish_pond_id"
type = "u32"
key = true

[[models.members]]
name = "fish_id"
type = "u32"
key = true

[[models.members]]
name = "commit_timestamp"
type = "u64"
key = false

[[models.members]]
name = "reveal_timestamp"
type = "u64"
key = false

[[models.members]]
name = "count"
type = "u32"
key = false
