kind = "DojoModel"
class_hash = "0x36a1c982bdf821be20190700ec1c9ce526dea67aed0a5297983f775b03e60ba"
original_class_hash = "0x36a1c982bdf821be20190700ec1c9ce526dea67aed0a5297983f775b03e60ba"
abi = "manifests/dev/base/abis/models/tonatuna-FishPond-6253e2c7.json"
tag = "tonatuna-FishPond"
qualified_path = "tonatuna::models::index::fish_pond"
manifest_name = "tonatuna-FishPond-6253e2c7"

[[members]]
name = "id"
type = "u32"
key = true

[[members]]
name = "fish_population"
type = "u32"
key = false

[[members]]
name = "max_fish_id"
type = "u32"
key = false

[[members]]
name = "daily_catch_limit"
type = "u32"
key = false

[[members]]
name = "rare_fish_chance"
type = "u8"
key = false

[[members]]
name = "daily_catches"
type = "u32"
key = false
