kind = "DojoModel"
class_hash = "0x5d1e34fed7ae0fb2b98222f698af52ff1f528dd2bc7c9e66722e336313cb7d6"
original_class_hash = "0x5d1e34fed7ae0fb2b98222f698af52ff1f528dd2bc7c9e66722e336313cb7d6"
abi = "manifests/dev/base/abis/models/tonatuna-Player-24470676.json"
tag = "tonatuna-Player"
qualified_path = "tonatuna::models::index::player"
manifest_name = "tonatuna-Player-24470676"

[[members]]
name = "id"
type = "felt252"
key = true

[[members]]
name = "name"
type = "felt252"
key = false

[[members]]
name = "bait_balance"
type = "u32"
key = false

[[members]]
name = "fish_caught"
type = "u32"
key = false

[[members]]
name = "daily_attempts"
type = "u8"
key = false

[[members]]
name = "position"
type = "Vec2"
key = false
