kind = "DojoModel"
class_hash = "0x3b98b467b59555f321c490645a78765ca8ba1edaee023fb0db47682c48a18e5"
original_class_hash = "0x3b98b467b59555f321c490645a78765ca8ba1edaee023fb0db47682c48a18e5"
abi = "manifests/dev/base/abis/models/tonatuna-DirectionsAvailable-4cb6d4a7.json"
tag = "tonatuna-DirectionsAvailable"
manifest_name = "tonatuna-DirectionsAvailable-4cb6d4a7"

[[members]]
name = "player"
type = "ContractAddress"
key = true

[[members]]
name = "directions"
type = "Array<Direction>"
key = false
